# Generated by Django 3.2.6 on 2024-02-12 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('col', models.CharField(default='000000', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('font', models.CharField(max_length=255)),
                ('img', models.TextField(default='no image')),
                ('iskansai', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.TextField(default='no image')),
                ('txt', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eemon_551_app.genre')),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eemon_551_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.BooleanField()),
                ('qes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eemon_551_app.question')),
                ('user_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eemon_551_app.userdata')),
            ],
        ),
    ]
